### ISSUE TITLE
Main site link says 'Application name'

### ISSUE THREAD

**Issue by Andorbal** [Claim-Academy/prospect-manager-NET041815#17]
We probably want our application to be branded better than this.  Change 'Application Name' to 'Prospect Manager' and change the copyright at the bottom of the page to say 'Claim Academy' instead of 'My ASP.NET Application'

**Comment by TylerSadler** [comment]
I can do this one real quick

**Comment by TylerSadler** [comment]
Finished the fix. Waiting to create pull request till I do more issues though.

**Comment by Andorbal** [comment]
Please create a pull request per issue; it makes it easier to merge.  It also keeps things separate so that if one fix works and the other doesn't I don't have to reject everything.

**Comment by TylerSadler** [comment]
OK. I just did
