### ISSUE TITLE
Improve styling of the alphabet list

### ISSUE THREAD

**Issue by Andorbal** [Claim-Academy/prospect-manager-NET041815#33]
The alphabet list is all squished together on all the pages that it's on.  It would be nice if we could add some styling that put some space between the letters.  Take a look at the [Bootstrap CSS](http://getbootstrap.com/css/) and [Bootstrap components](http://getbootstrap.com/components/) for potentially helpful styles you can use.

**Comment by rcaba002** [comment]
I will do this one!

**Comment by rcaba002** [comment]
Completed

**Comment by Andorbal** [comment]
Nice job!
