### ISSUE TITLE
Improve the styling of the 'Add contact to meeting' screen

### ISSUE THREAD

**Issue by Andorbal** [Claim-Academy/prospect-manager-NET041815#34]
We don't have any line breaks between the contact list checkboxes and the submit button is on the same line as well.  It would be nice if this looked better.

**Comment by TylerSadler** [comment]
added line break

**Comment by Andorbal** [comment]
Add a comment to the issue before you start working on the issue so that no one else works on it while you are working on it.  It makes a difference, even for small tasks like this one.  Also, did you add "#34" to your commit comment?

**Comment by TylerSadler** [comment]
I added it to the pull request description forgot it was suppose to be in
the commit comment. And I normally do, only reason I did not is because no
one else it here. I will from now on though. Have a good day.

**Comment by Andorbal** [comment]
Commit looks good, though in addition to the '#34', add a meaningful description of what the commit is for.
