### ISSUE TITLE
Add alphabet links to the contact list page

### ISSUE THREAD

**Issue by Andorbal** [Claim-Academy/prospect-manager-NET041815#7]
We have a list of alphabet links on the home page of the application.  We should probably also display the list of links on the contact index view as well.  Once this is working, try to extract the listing of the letters into a shared partial view so that it can be re-used on the home index view and the contact index view.

**Comment by rcaba002** [comment]
I will attempt this one.

**Comment by sethwolter** [comment]
Working on this now!

**Comment by sethwolter** [comment]
Still working on this.. very close now...

**Comment by sethwolter** [comment]
I got it... I got it.. I got it... I don't got it... close but there is an error I can't resolve.
