### ISSUE TITLE
Add meeting duration

### ISSUE THREAD

**Issue by Andorbal** [Claim-Academy/prospect-manager-NET041815#9]
We currently store the start time for a meeting, but it doesn't say anything about when the meeting will end.  So we should add an end date to meeting.  We'll need to add a property to the Meeting class, update the views to allow editing/displaying, and update the [Bind] attribute in the controller actions to include the property.

Don't forget to update the seed data!

**Comment by TylerSadler** [comment]
Ill do this one

**Comment by TylerSadler** [comment]
finished
